version: "3.9"
services:
  ubuntu24:
    build: .
    container_name: ubuntu24-term
    hostname: ubuntu24
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/workspace
    mem_limit: ${CONTAINER_RAM:-1g}
    cpus: ${CPU_CORES:-2}
    shm_size: '256m'
